# -*- mode: ruby -*-
# vi: set ft=ruby :

masters = [
    {
        :name => "master",
        :eth1 => "10.200.130.11",
        :mem => "1024",
        :cpu => "1"
    }
]

agents = [
    {
        :name => "agent",
        :eth1 => "10.200.130.101",
        :mem => "4096",
        :cpu => "4"
    },
    {
        :name => "agent",
        :eth1 => "10.200.130.102",
        :mem => "4096",
        :cpu => "4"
    },
    {
        :name => "agent",
        :eth1 => "10.200.130.103",
        :mem => "4096",
        :cpu => "4"
    }
]

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
 
  config.vm.provision "shell", path: "init.sh"
  masters.each_with_index do |opts,index|
   config.vm.define "master-#{index}" do |master|
      master.vm.hostname = "pacemaker-master-#{index}"
      master.vm.network "private_network", ip: opts[:eth1]
      master.vm.provision "shell" do |s| 
        s.path = "mesos/init-master.sh"
        s.args = opts[:eth1]
      end
      master.vm.provider :libvirt do |libvirt|
        libvirt.username = "root" 
        libvirt.password = "pacemaker" 
        libvirt.cpus = opts[:cpu]
        libvirt.memory = opts[:mem]
        libvirt.default_prefix = "mesos" 
      end
    end
  end
  
  agents.each_with_index do |opts,index|
    config.vm.define "agent-#{index}" do |agent|
      agent.vm.hostname = "pacemaker-agent-#{index}"
      agent.vm.network "private_network", ip: opts[:eth1]
      agent.vm.provision "shell" do |s| 
        s.path = "mesos/init-agent.sh"
        s.args = ["10.200.130.11", opts[:eth1]]
      end
      agent.vm.provider :libvirt do |libvirt|
        libvirt.username = "root" 
        libvirt.password = "pacemaker" 
        libvirt.cpus = opts[:cpu]
        libvirt.memory = opts[:mem]
        libvirt.default_prefix = "mesos" 
      end
    end
  end

end
